config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, except: [:index]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, :live, presence: true

  belongs_to :band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password

  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6 }, allow_nil: true
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password # this is just so we can validate password length
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password) #since we don't have their passwords stored, we still need a way to verify their password
    pass_hash = BCrypt::Password.new(self.password_digest) #converts password digest back to bcrypt object
    pass_hash.is_password?(password)  #runs is_password to see if the password string matches that bcrypt object
  end

  def self.find_by_credentials(email, password) #I believe this will be used for verification later while logging in
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    render :new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def log_in_user!(user)
    user.reset_session_token! #resets their db session token
    session[:session_token] = user.session_token #sets their cookie sesh token to the one in db
  end

  def log_out_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    band = Band.new(band_params)

    if band.save
      redirect_to bands_url
    else
      flash.now[:errors] = band.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    band = Band.find_by(id: params[:id])

    if band.update(name: params[:band][:name])
      redirect_to bands_url
    else
      flash.now[:errors] = band.errors.full_messages
      render :edit
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def destroy
    band = Band.find_by(id: params[:id])
    band.delete
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user
      log_in_user!(user)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    log_out_user!(current_user)
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in_user!(user)
      redirect_to bands_url
    else
      flash.now[:errors] = user.errors.full_messages #makes a key value pair exist in the flash hash for just this same cycle.
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>New album!</h1>

<form action="" method="post">

</form>

app/views/bands/edit.html.erb
<h1>Edit band!</h1>

<form action="<%=band_url(@band)%>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="text" name="band[name]" value="<%= @band.name %>">
  <input type="submit" value="Submit">
</form>

app/views/bands/index.html.erb
<h2 class="title subtitle">Bands</h2>
<section class="band-options">
  <% @bands.each do |band| %>
      <button class="main-button" type="button"><%= band.name %></button>
  <% end %>
</section>

<p><%= link_to "New band", new_band_url %></p>

app/views/bands/new.html.erb
<h1 class="title subtitle">New band!</h1>

<form class="new-band-form" action="<%=bands_url%>" method="post">
  <ul class="field">
    <label for="name">Name</label>
    <input type="text" name="band[name]">
  </ul>
  <input type="submit" value="Submit">
</form>

app/views/bands/show.html.erb
<p><%= @band.name %></p>

<%= button_to "Edit", edit_band_url(@band), method: :get %>
<%= button_to "Destroy", band_url(@band), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <main>
      <h1 class="title main-logo">Music App</h1>
      <nav class="main-nav">
        <% if logged_in? %>
        <%= button_to "Take me Home", bands_url, method: :get %>
        <div class="login-status">
          <p>Logged in as: <%= current_user.email %></p>
        </div>
        <%= button_to "Sign Out", session_url, method: :delete %>
        <% end %>
      </nav>
    <%= yield %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <li><%=error%></li>
      <% end %>
    <% end %>
    <br>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<h2 class="title subtitle">New User</h2>

<%= button_to "Go to sign in!", new_session_url, method: :get %>

<form class="credentials-form" action="<%=users_url%>" method="post">
  <ul class="field">
    <label for="email">Email</label>
    <input type="text" name="user[email]">
  </ul>

  <ul class="field">
    <label for="password">Password</label>
    <input type="text" name="user[password]">
  </ul>

  <input type="submit" value="Sign-up">
</form>

app/views/users/show.html.erb
hello <%= @user.email %>